services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: jm_data_os
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - jm_data_os_pg:/var/lib/postgresql/data

volumes:
  jm_data_os_pg:
